# PostgreSQL Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/apargo_storage_mysql
    username: root
    password: meenagaming12@#

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
